services:

  prometheus:
    image: quay.io/prometheus/prometheus:v3.1.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus_scrape_configs.yml:/etc/prometheus/prometheus.yml

  jaeger:
    image: jaegertracing/all-in-one:1
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "14268"       # Accept thrift spans
      - "14250"       # Accept gRPC spans
      - "4317"        # Otel gRPC

  otel-collector:
    image: otel/opentelemetry-collector:0.119.0
    container_name: otel-collector
    command:
      - "--config=/conf/otel-collector-config.yml"
    volumes:
      - ./config/otel-collector-config.yml:/conf/otel-collector-config.yml
    ports:
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
    depends_on:
      - jaeger

  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - jaeger
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data: