spring:
  application:
    name: user_service
  config:
    import: logging.yml
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/user_service?serverTimezone=UTC}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  flyway:
    output-query-results: true
    create-schemas: false
    clean-disabled: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        query:
          fail_on_pagination_over_collection_fetch: true
  security:
    oauth2:
      client:
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID:baaef96d4123ef7b0186}
            client-secret: ${GITHUB_CLIENT_SECRET:095b0962736c8c78211afc5b7f88fade48b33d9d}
            redirect-uri: ${GITHUB_REDIRECT_URI:http://localhost:8180/login/oauth2/code/github}
            scope:
              - read:user
              - user:email
          google:
            client-id: ${GOOGLE_CLIENT_ID:52805631359-tamguap0crreiirs9vo2ge8k6ft78tp8.apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET: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}
            redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8180/login/oauth2/code/google}
            scope:
              - openid
              - profile
              - email
      authorizationserver:
        client:
          postman:
            registration:
              client-id: postman
              client-authentication-methods:
                - "none"
              authorization-grant-types:
                - "authorization_code"
              redirect-uris: https://oauth.pstmn.io/v1/callback
              post-logout-redirect-uris: https://oauth.pstmn.io/v1/callback
              scopes:
                - openid
            require-authorization-consent: false
            require-proof-key: true
            token:
              access-token-time-to-live: PT2H

server:
  port: 8180